spring:
  application:
    name: cms
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kss_test}
    username: ${DB_USER:lhuser}
    password: ${DB_PASSWORD:lhpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USER:veekthorcodes@gmail.com}
    password: ${MAIL_PASSWORD:ofdzzxqbjvsqtjmt}
    properties:
      mail:
        smtp:
          auth: true
          ssl: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
jwt:
  secret: ${JWT_SECRET:bAOzFxCO7OTGBDF5hTGJZlRPUlMJ5MIt/qSfKGiqfHI=}
  expiration: 86400000
springdoc:
  swagger-ui:
    persisteAuthorization: true
    filter: true
    path: /swagger-ui.html
app:
  client-url: ${CLIENT_URL:http://localhost:5173}
