spring:
  application:
    name: cms
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
springdoc:
  swagger-ui:
    persisteAuthorization: true
    filter: true
    path: /swagger-ui.html
app:
  client-url: ${CLIENT_URL}
